import { Octokit } from '@octokit/rest';
import type { PRDiff } from '../types/index.js';

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

/**
 * Get PR diff from GitHub
 * @param owner - Repository owner
 * @param repo - Repository name
 * @param prNumber - Pull request number
 * @returns Array of file diffs
 */
export async function getPRDiff(
  owner: string,
  repo: string,
  prNumber: number
): Promise<PRDiff[]> {
  try {
    const { data: files } = await octokit.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber,
    });

    return files.map((file) => ({
      filename: file.filename,
      status: file.status,
      additions: file.additions,
      deletions: file.deletions,
      changes: file.changes,
      patch: file.patch,
    }));
  } catch (error) {
    console.error('Error fetching PR diff:', error);
    throw error;
  }
}

/**
 * Post review comment to PR
 * @param owner - Repository owner
 * @param repo - Repository name
 * @param prNumber - Pull request number
 * @param body - Comment body
 */
export async function postReviewComment(
  owner: string,
  repo: string,
  prNumber: number,
  body: string
): Promise<void> {
  try {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  } catch (error) {
    console.error('Error posting review comment:', error);
    throw error;
  }
}

/**
 * Format review response as markdown comment
 * @param summary - Review summary
 * @param comments - Individual file comments
 * @param assessment - Overall assessment
 * @returns Formatted markdown string
 */
export function formatReviewComment(
  summary: string,
  comments: Array<{ path: string; line: number; body: string }>,
  assessment: string
): string {
  let markdown = `## 🤖 AI Code Review\n\n`;
  markdown += `### Summary\n${summary}\n\n`;

  if (comments.length > 0) {
    markdown += `### Detailed Comments\n\n`;
    comments.forEach((comment) => {
      markdown += `**\`${comment.path}\` (Line ${comment.line})**\n`;
      markdown += `${comment.body}\n\n`;
    });
  }

  markdown += `### Overall Assessment\n`;
  const emoji =
    assessment === 'LGTM'
      ? '✅'
      : assessment === 'Needs Changes'
      ? '⚠️'
      : '💬';
  markdown += `${emoji} **${assessment}**\n\n`;
  markdown += `---\n`;
  markdown += `*Generated by Claude AI*`;

  return markdown;
}
